apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.ovverideName }}-cluster-custom
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Values.ovverideName }}-cluster
    app.kubernetes.io/name: memsql-cluster
spec:
  ports:
  - name: memsql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Values.ovverideName }}-cluster
    app.kubernetes.io/name: memsql-cluster
  type: ClusterIP